### ISSUE TITLE
Invite Filter Regex Error

### ISSUE THREAD

**Issue by RealSGII2** [Blackcatmaxy/Botcatmaxy#123]
**Describe the bug**
The invite regex detects some of Discord's URLs as invites, for example https://discord.com/security is considered an invite.

**Expected behavior**
Official Discord URLs should not be filtered.

**Screenshots**
![image](https://user-images.githubusercontent.com/41650610/110169479-98b8e380-7dad-11eb-8a6f-df4b32c72bc4.png)

**Additional context**
This happened in BGD. Message link: https://discord.com/channels/172119104092635136/172119104092635136/817285115935457290

**Comment by Blackcatmaxy** [comment]
While the regex is faulty, it is important to acknowledge that "security" is an invite code and discord.gg/security is apparently a valid invite
