### ISSUE TITLE
autofilter error

### ISSUE THREAD

**Issue by BeagleJonas** [Blackcatmaxy/Botcatmaxy#127]
**Describe the bug**
BCM failed to remove message with a filtered word in it

**Expected behavior**
BCM correctly removes the message

**Screenshots**
![image](https://user-images.githubusercontent.com/73210695/116312166-1845ac00-a77a-11eb-833c-4908a720ad01.png)

**Additional context**
autofilter's been working all day except in this specific instance, + the message should probably append, not replace*

**Comment by Blackcatmaxy** [comment]
Seems like a Discord API failure where the message failed to delete and then the modify function failed to get current content. Append is correctly programmed.

**Comment by Blackcatmaxy** [comment]
We have transitioned to a Discord.NET major update, and there have been no reports or errors like this. If any similar issues arise we can reopen this issue provided more data than this minimal amount is provided. If someone experiences this again, please mention:
- Intensity of channel activity
- Guild, Channel, Message, and User IDs
- Content of message in a spoiler
