### ISSUE TITLE
bug: Usernames following non-standard characters fails commands

### ISSUE THREAD

**Issue by RealSGII2** [Blackcatmaxy/Botcatmaxy#129]
**Describe the bug**
A command mentioning a user will throw an exception if said user's name contained non-standard characters.

**Expected behavior**
The user should be banned.

**Screenshots**
![image](https://user-images.githubusercontent.com/41650610/117093027-a094f580-ad14-11eb-890f-0ceaa3fe5edc.png)

**Additional context**
User Name: `PopeXavierTheFirst✓ᵛᵉʳᶦᶠᶦᵉᵈ™®©`
User ID: 297128725798060034
Guild ID: 696814795793498284
Channel ID: 696814795793498287

**Comment by Blackcatmaxy** [comment]
If the issue caused by unicode characters how has this not shown up before? The error is extremely unusual and seems to indicate something deeper.

**Comment by Blackcatmaxy** [comment]
Did more checking, issue seems to have happened before but only after v15 and still to rarely in my opinion too be with all unicode. Definitely need to spend time testing which I don't have.

**Comment by BeagleJonas** [comment]
Issue happens as well with standard character usernames, ex. aeuaeu#5631. Error occurred when using ID, not mention.
![image](https://user-images.githubusercontent.com/73210695/117555001-5f108d00-b029-11eb-9609-20efb565ee22.png)

**Comment by Blackcatmaxy** [comment]
Are all instances known from !ban?

**Comment by BeagleJonas** [comment]
!tempban worked perfectly fine for the aeuaeu guy (the problem was found when trying to convert the temp to a perm ban)

**Comment by Blackcatmaxy** [comment]
Stacktrace
> ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task\`1<Discord.IUserMessage> Discord.IMessageChannel.SendMessageAsync(System.String, Boolean, Discord.Embed, Discord.RequestOptions)'.
   at Interactivity.InteractivityService.SendConfirmationAsync(Confirmation confirmation, IMessageChannel channel, Nullable\`1 timeout, IUserMessage message, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Interactivity.InteractivityService.SendConfirmationAsync(Confirmation confirmation, IMessageChannel channel, Nullable`1 timeout, IUserMessage message, CancellationToken token)
   at BotCatMaxy.ModerationCommands.Ban(UserRef userRef, String reason) in /home/maxy/RiderProjects/Botcatmaxy/src/BotCatMaxy/Components/Moderation/ModerationCommands.cs:line 480
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   --- End of inner exception stack trace ---

Seems like some really weird issue with Interactivity and asking about the command. In the first case it was probably with trying to ask if Taxalotl was sure they didn't mean to use `!tempban`, and in this case it's trying to let you know the user is tempbanned and ask if you want to perm ban.

**Comment by Blackcatmaxy** [comment]
@RealSGII2 we could upgrade `Discord.InteractivityAddon` to latest prerelease (considering latest stable which we're currently using is 10 months old) but might cause more issues, you have any other ideas or do you think we should just go for it?

**Comment by RealSGII2** [comment]
I say try it and test it. If it encounters any exceptions in production we'll have to revert.

> Are all instances known from !ban?

Yes for the original report.

**Comment by Blackcatmaxy** [comment]
I don't like how this has popped out of nowhere when it used to be stable, still feel like there's more to it

**Comment by Blackcatmaxy** [comment]
Looked in Git blame and I remembered how we used to have InteractivityService on the first prerelease which I'm now guessing didn't have this problem and it seems like the first instance of this error in the logs showed up a week after the commit changing to stable.

**Comment by BeagleJonas** [comment]
![image](https://user-images.githubusercontent.com/73210695/119873629-ba2ff400-bef2-11eb-89be-7b15d3fe77c1.png)
Not directly failing the command, but the command timed out for user 'olddude#2124 (844218261259550720.)' The command worked perfectly fine for another user but timed out when presented with him.

**Comment by Blackcatmaxy** [comment]
This was completely Discord API related with the REST request being timed out for taking too long by the Discord.NET library. The error is not related to the user as the line that threw the exception was getting the guild bans

**Comment by Blackcatmaxy** [comment]
We have transitioned to a completely different interactivity package as well as a Discord.NET major update, and there have been no reports or errors like this. If any similar issues arise we can reopen this issue.
