### ISSUE TITLE
Incorrect Highlighting in Modlog for Filtered Word

### ISSUE THREAD

**Issue by clerically** [Blackcatmaxy/Botcatmaxy#135]
**Describe the bug**
The bot incorrectly highlighted the "ass" in "massive" (m**[ass]**ive) instead of the ass that is not inside of another word. This isn't really a big issue in my opinion since it's still clear what the filtered word was.

**Expected behavior**
BotCatMaxy should highlight the word "ass" outside of the word "massive", as the word "ass" is not toggled on for containword.

**Screenshots**
![image](https://user-images.githubusercontent.com/75017384/122503324-1693aa00-cfad-11eb-8f6b-ac8fea05eb18.png)

**Additional context**
Log Link: https://canary.discord.com/channels/172119104092635136/427862871138107392/855287194779516928

**Comment by Blackcatmaxy** [comment]
There are truly tons of edge cases with this system and while we've set up most of them to fail, this might just be worth it to ignore as you said
