### ISSUE TITLE
Cannot count infractions/Compile multiple infractions to 1 message

### ISSUE THREAD

**Issue by n00btvb3** [Blackcatmaxy/Botcatmaxy#140]
**Describe the bug**
Bot failing to count infractions correctly as well as failing to delete mass-warns and compile them into 1 message

**Expected behavior**
1 - Appropriately counting the infractions
2 - Deleting repeated instances of warns in a short time period and editing the original message to compile them

**Screenshots**
![Discord_7xlMQ4s5uj](https://user-images.githubusercontent.com/87041104/124661703-89a78680-deb0-11eb-8fad-a45ba3f19cfc.png)
![Discord_AFm2HGNU8s](https://user-images.githubusercontent.com/87041104/124661840-bbb8e880-deb0-11eb-94c4-1a608607b234.png)

**Additional context**
BGD was @everyone'd (owner's birthday) resulting in a lot of people talking/mentioning a user in quick succession

**Comment by Blackcatmaxy** [comment]
This is a very delicate system that relies on getting past messages, and in a scenario of intense activity the bot would be experiencing preemptive ratelimits. 

We cannot guarantee stability of QOL features such as this without a great deal of work that would truly be better spent elsewhere while moderators should be doing their job and setting a slowmode keeping in mind that BCM has the command `!setslowmode` which allows precise settings such as just `2 seconds` which can already give the bot a lot of space.
