### ISSUE TITLE
Reports feature in general

### ISSUE THREAD

**Issue by BeagleJonas** [Blackcatmaxy/Botcatmaxy#143]
**Describe the bug**
wish I knew what the hell was happening, I set up bcm reporting in my testing server to test exactly how the report feature works, before proposing the idea to BGD staff for using it. upon conducting tests, BCM would send random messages to the report channel after I used !report in dms and didn't get to type anything before BCM just 'sent' my lack of a message

**Expected behavior**
BCM to wait until I actually sent a message before sending a ghost report

**Screenshots**
![image](https://user-images.githubusercontent.com/73210695/134078152-0c56a534-61d7-44cd-aa06-9661aeaddc15.png)
![image](https://user-images.githubusercontent.com/73210695/134078344-d52b62b2-c723-4658-b658-7f03fd4a7f6c.png)

**Additional context**
I did receive a DM from another user while testing the reports, but none of the messages sent by me nor them in any server matched the 'reported' messages

THE SECOND REPORT MESSAGE WAS ACTUALLY SENT BY ME, I MANAGED TO GET IT IN BEFORE IT 'CLOSED'

**Comment by Blackcatmaxy** [comment]
This is an issue with the Interactivity code in the live version (fixed in dev branch). I can give a binary and instructions on how to test if you want to help get the update out as I've been too busy recently.

**Comment by Blackcatmaxy** [comment]
Noting commit 8fc9e38773ebff5e46b5fe2f6ad3347298527481 labeled as fixing
