### ISSUE TITLE
Converting !mute and !tempmute to new Discord Timeout feature.

### ISSUE THREAD

**Issue by BeagleJonas** [Blackcatmaxy/Botcatmaxy#144]
**Describe the solution you'd like**
Discord introduced a new built-in "mute" feature with according permissions, as the mute commands are currently tied to the kick permission, it would be smart to start converting it over to the timeout permission. 

**Additional context**
Would require a month+ long deprecation notice where both the kick and timeout permission are supported to allow servers to transition to the new permissions.

**Comment by Blackcatmaxy** [comment]
Also more potential just came to mind, what if we add a `!timeout` and `!timeoutwarn` command that use timeouts taking advantage of Discord's timeouts while still keeping tempmutes. There was a feature request for reaction mutes for example and this way servers could use timeouts for traditional tempmutes and then customize the tempmute role for whatever purpose they need?

**Comment by Blackcatmaxy** [comment]
Commit 6ed198b627162a96e4a3ffa3cf537bf07a03f15e delays this but `Discord.NET Labs` was never meant for production and hopefully `Discord.NET V3` will have a fast enough update cycle to get this in soon.

**Comment by Blackcatmaxy** [comment]
On current evaluation this would be simple, but at least Discord.NET does not expose functionality that would allow setting/getting timeouts without a GuildUser object meaning that we would be losing functionality of tempmuting users who have left a guild. 

If anyone would like such a feature at that cost I am confident the maintenance burden would be small enough to create a toggle but this seems like a big weakness to not be able to timeout users if they leave.
