### ISSUE TITLE
BotCatMaxy initializes changing a tempban to a ban before getting a response.

### ISSUE THREAD

**Issue by BeagleJonas** [Blackcatmaxy/Botcatmaxy#148]
**Describe the bug**
When using !ban on a user that is already tempbanned, BCM asks for confirmation to proceed with overwriting the tempban, however BCM just initializes the ban before getting a response. Oddly this isn't consistent and has happened 2 out of 3 attempts to reproduce.

**Expected behavior**
BCM should wait for the response to the prompt before initializing the ban.

**Screenshots**
![image](https://user-images.githubusercontent.com/73210695/150623120-bd44e13a-ab07-4e79-8460-32ea13fa238d.png)

**Additional context**
Attempted to reproduce and first attempt failed to reproduce this outcome, but a second attempt did reproduce it.

**Comment by Blackcatmaxy** [comment]
Work started on commit 05ccaba27f1e4a23dcd83908fd65265212a34e80
