### ISSUE TITLE
"High" slowmode intervals cause the bot to remove slowmode in the channel

### ISSUE THREAD

**Issue by clerically** [Blackcatmaxy/Botcatmaxy#153]
**Describe the bug**
Slowmode intervals greater than 60 seconds cause the bot to remove the slowmode in the channel

**Expected behavior**
The bot should set the slowmode to the specified time

**Screenshots**
![image](https://user-images.githubusercontent.com/75017384/166622862-fe3ac4c1-1527-41ea-8e23-0b9f3aa806ed.png)
![image](https://user-images.githubusercontent.com/75017384/166622870-1ef42678-fa52-4a11-adf1-2ec054358d98.png)

**Comment by Blackcatmaxy** [comment]
Fixed in #154
