### ISSUE TITLE
Filter command not showing filter

### ISSUE THREAD

**Issue by Thearch1** [Blackcatmaxy/Botcatmaxy#159]
**Describe the bug**
Filter command !filter info e + !confirm not showing all words within the filter
**Expected behavior**
What should be showing: https://cdn.discordapp.com/attachments/996184236530876506/1031013757498953868/Screenshot_20221015-211136_Discord.jpg

**Screenshots**
What was shown: https://gyazo.com/f9c11143da4c12c1dc515876505a5208

**Comment by RealSGII2** [comment]
Duplicate of #158
