### ISSUE TITLE
Log bans in infraction log.

### ISSUE THREAD

**Issue by Reecemanw** [Blackcatmaxy/Botcatmaxy#162]
When viewing a users infractions not being able to see bans on the list makes keeping track of a ban per x weight system quite hard. Having bans be displayed amongst the warns and what weight the user had when they were banned would be a tremendous help for moderating as to save fishing through ban logs to find if a user has already been banned for total weight or not.

**Comment by Blackcatmaxy** [comment]
Duplicate of #99
