### ISSUE TITLE
Warn Ephemerals

### ISSUE THREAD

**Issue by RealSGII2** [Blackcatmaxy/Botcatmaxy#169]
**Is your feature request related to a problem? Please describe.**
A common pattern in servers owned by Outoforderfoxy is that punishments are handed out in a private channel.

**Describe the solution you'd like**
Allow a method to send the punishment response as an ephemeral message. This could be:
- Separate commands using the same code
- Boolean parameters in the commands. 

**Describe alternatives you've considered**
There is no clear alternative to this, other than to not implement it.

**Additional context**
N/A

**Comment by Blackcatmaxy** [comment]
The issue with an ephemeral warn is that there is no message for the warn to be linked to - perhaps a context menu option might be better than any slash command option.

**Comment by RealSGII2** [comment]
Is there a reason to keep a warn message done in a separate channel? It shows no context of the message(s) that prompted the warn.

**Comment by Blackcatmaxy** [comment]
In my experience when moderating there was often moderator discussion in the staff channel that was the reason it was done privately in that channel. Plus the context menu option seems like a straight plus over slash commands except for discoverability.

**Comment by RealSGII2** [comment]
Alright.
