### ISSUE TITLE
Some messages with image embeds will not show correctly in the log

### ISSUE THREAD

**Issue by TheDreg27** [Blackcatmaxy/Botcatmaxy#27]
When deleting a message with an embed, the bot will (sometimes) log it as "Embed cannot be displayed", and also fail to load any text that goes along with the message.

**Comment by Blackcatmaxy** [comment]
I can do more testing but this is a fail-safe to log messages that would otherwise be null. I can try to log more of the messages, but this message will still be seen on messages that only have pictures until #14 is done
