### ISSUE TITLE
Have identifiers for users so that it can track across servers.

### ISSUE THREAD

**Issue by aeiou642** [Blackcatmaxy/Botcatmaxy#34]
In more context, if someone was to get punished multiple times in Server 1 but was also in Server 2,  Server 2 mods could see infractions to see a user's actions.

**Comment by aeiou642** [comment]
To add on, it shouldn't be anything necessarily complicated, just a hash that the bot can either link a discord account to or something like RoVer that has you manually enter in an account.

**Comment by Blackcatmaxy** [comment]
Won't add without commission or pull request due to low demand and it not being quite that simple
