### ISSUE TITLE
Pinging banned members prevents you from talking

### ISSUE THREAD

**Issue by ext3nded** [Blackcatmaxy/Botcatmaxy#45]
[![Screenshot from Gyazo](https://gyazo.com/a75ee064d5107b32159fa33f4c851542/raw)](https://gyazo.com/a75ee064d5107b32159fa33f4c851542)

**Comment by Blackcatmaxy** [comment]
That's a discord issue that has nothing to do with my bot. If you have the muted role then mee6 might be responsible
