### ISSUE TITLE
Add unmute command

### ISSUE THREAD

**Issue by iINeonDubstepIi** [Blackcatmaxy/Botcatmaxy#60]
Just Incase you mute the wrong person by mistake.

**Comment by Blackcatmaxy** [comment]
This is mostly not needed because only admins would likely have it and the bot recognizes the end of a tempmute if someones muted role is removed

**Comment by Blackcatmaxy** [comment]
Nobody has every truly requested this after being informed of the ability to just remove the muted role, and per #144 as we transition to Discord's new timeouts, they can be ended from the client.

**Comment by clerically** [comment]
Obsolete with the new Discord timeout feature
