### ISSUE TITLE
Add an option to disable certain/all logs for a user/bot/channel

### ISSUE THREAD

**Issue by iINeonDubstepIi** [Blackcatmaxy/Botcatmaxy#82]
Ex. Disable every log from a bot (like Cluck in the vesteria discord server)
Ex2. ignore deleted messages from an announcement channel..?

**Comment by Blackcatmaxy** [comment]
I have discussed this with other people, the point of logs is for transparency and it's not that important to ignore logs. Bots like Cluck should be made to work in DMs anyway.
