### ISSUE TITLE
Error in report commands

### ISSUE THREAD

**Issue by Peter-EXE** [Blackcatmaxy/Botcatmaxy#92]
I was testing the report system in my storage server, however, I discovered there is an error. BotCatMaxy owns the Administrator role permission so everything should work fine. 
![Screenshot 2020-06-09 at 3 29 36 AM](https://user-images.githubusercontent.com/53822056/84118927-ac434380-aa01-11ea-9130-0549cffdaff6.png)

**Comment by Blackcatmaxy** [comment]
Fixed in 3428fd62fac2a496de2188bea60d8d4b761ab67b
